"""
db_create.py

Creates the EBG tables in Oracle according to the provided schema.
This script is intentionally focused on DDL only and will create the
following tables when executed against the configured Oracle database:

- ebg_requests (minimal table to satisfy FKs)
- ebg_issuances
- ebg_amendments

Each CREATE TABLE is executed inside an anonymous PL/SQL block that
ignores the "table already exists" error so the script is idempotent.
"""
import oracledb
from utils.logging_utils import logger
from config.config import config


DDL_EBG_REQUESTS = """
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE ebg_requests (
        id VARCHAR2(36) PRIMARY KEY,
        created_at TIMESTAMP
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
"""


DDL_EBG_ISSUANCES = """
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE ebg_issuances (
        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        request_id VARCHAR2(36),
        bg_ref_num VARCHAR2(50),
        type_of_bg VARCHAR2(30),
        bg_amount NUMBER(18,2),
        bg_currency CHAR(3),
        bg_effective_date DATE,
        guarantee_from_date DATE,
        guarantee_to_date DATE,
        claim_end_date DATE,
        claim_lodgement_place VARCHAR2(100),
        received_date DATE,
        applicant_details CLOB,
        beneficiary_details CLOB,
        beneficiary_ifsc VARCHAR2(20),
        beneficiary_bank_details CLOB,
        issuing_branch_ifsc VARCHAR2(20),
        issuing_branch_name_address CLOB,
        sender_to_receiver_info VARCHAR2(100),
        smsa_text CLOB,
        purpose_of_guarantee VARCHAR2(255),
        description_of_contract CLOB,
        place_of_payment VARCHAR2(100),
        amount_paid NUMBER(18,2),
        date_of_payment DATE,
        stamp_duty_paid VARCHAR2(10),
        estamp_certificate_number VARCHAR2(100),
        estamp_date DATE,
        guarantee_form_num VARCHAR2(50),
        state_code VARCHAR2(10),
        to_be_held_in_demat NUMBER(1),
        demat_account_num VARCHAR2(50),
        custodian_service_provider VARCHAR2(100),
        article_number VARCHAR2(50),
        created_at TIMESTAMP
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
"""


DDL_EBG_AMENDMENTS = """
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE ebg_amendments (
        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        request_id VARCHAR2(36),
        bg_ref_num VARCHAR2(50),
        original_bg_num VARCHAR2(50),
        num_of_amendment NUMBER(5),
        amendment_date DATE,
        amendment_details CLOB,
        date_of_issuance DATE,
        received_date DATE,
        remarks VARCHAR2(255),
        applicant_details CLOB,
        beneficiary_details CLOB,
        beneficiary_ifsc VARCHAR2(20),
        beneficiary_bank_details CLOB,
        issuing_branch_ifsc VARCHAR2(20),
        issuing_branch_name_address CLOB,
        bg_amount NUMBER(18,2),
        bg_expiry_date DATE,
        bg_claim_expiry_date DATE,
        sender_to_receiver_info VARCHAR2(100),
        smsa_text CLOB,
        place_of_payment VARCHAR2(100),
        amount_paid NUMBER(18,2),
        date_of_payment DATE,
        stamp_duty_paid VARCHAR2(10),
        stamp_duty_amt_paid NUMBER(18,2),
        estamp_certificate_number VARCHAR2(100),
        estamp_date DATE,
        state_code VARCHAR2(10),
        to_be_held_in_demat NUMBER(1),
        demat_account_num VARCHAR2(50),
        custodian_service_provider VARCHAR2(100),
        article_number VARCHAR2(50),
        created_at TIMESTAMP
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
"""


DDL_FK_ISSUANCES = """
BEGIN
    EXECUTE IMMEDIATE '
    ALTER TABLE ebg_issuances
    ADD CONSTRAINT fk_issuances_request
    FOREIGN KEY (request_id) REFERENCES ebg_requests(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-01430, -02289, -2275, -955) THEN
            RAISE;
        END IF;
END;
"""


DDL_FK_AMENDMENTS = """
BEGIN
    EXECUTE IMMEDIATE '
    ALTER TABLE ebg_amendments
    ADD CONSTRAINT fk_amendments_request
    FOREIGN KEY (request_id) REFERENCES ebg_requests(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-01430, -02289, -2275, -955) THEN
            RAISE;
        END IF;
END;
"""


def run_ddl(conn, ddl: str):
    cursor = conn.cursor()
    cursor.execute(ddl)
    cursor.close()


def main():
    cfg = config.oracle
    try:
        conn = oracledb.connect(
            user=cfg.USER,
            password=cfg.PASSWORD,
            dsn=cfg.DSN,
            config_dir=cfg.CONFIG_DIR,
            wallet_location=cfg.WALLET_LOCATION,
            wallet_password=cfg.WALLET_PASSWORD,
        )

        run_ddl(conn, DDL_EBG_REQUESTS)
        run_ddl(conn, DDL_EBG_ISSUANCES)
        run_ddl(conn, DDL_EBG_AMENDMENTS)
        # Add FKs after tables exist
        run_ddl(conn, DDL_FK_ISSUANCES)
        run_ddl(conn, DDL_FK_AMENDMENTS)

        conn.commit()
        conn.close()
        logger.info("EBG tables created/verified successfully")

    except Exception as e:
        logger.exception(f"Failed creating EBG tables: {e}")


if __name__ == "__main__":
    main()
